const locations = [

    {
        id: "1010",
        lat: 45.05702204168715,
        lng: -92.9591929076619,
        name: "Wildwood Amusement Park (1889 - 1932)",
        title: "Wildwood Amusement Park",
        image: "https://mnthen.com/locations/gallery/mahtomedi/wildwood/wildwood_2.jpg",
        creator: "Matt Reicher",
        city: "Mahtomedi",
        audio: "/audio/exhibit/wildwood.mp3", 
        tours: "history",
        summary: "Wildwood Amusement Park thrilled Twin Cities crowds for 30+ years with rides, shows & lakeside fun. It closed after years of financial issues. No ruins remain.",
        today: "Southeast corner of White Bear Lake",
        link: "https://mnthen.com/blog/place/wildwood.html",
        imageSource: "Image of the slide at Wildwood Park c. 1905 via MPRNews",
        additionalInfo: "Visitors didn’t just arrive by streetcar — some came by steamboat across White Bear Lake to spend the day swimming, dancing, and riding Wildwood’s coaster.",
        difficulty: 2
    },

    {
        id: "1011",
        lat: 44.922167523742054,
        lng: -93.10991227113067,
        name: "Michael 'Eyedea' Larsen (1981 - 2010)",
        title: "Michael 'Eyedea' Larsen",
        image: "https://mnthen.com/images/wsp_eyedea.webp",
        creator: "Matt Reicher",
        city: "St. Paul",
        audio: "/audio/exhibit/eyedea.mp3", 
        tours: "person",
        summary: "Michael “Eyedea” Larsen was a gifted battle rapper and hip-hop artist from St. Paul. He died at 28, but his music keeps his memory alive.",
        today: "Cherokee Regional Park",
        link: "https://mnthen.com/blog/people/eyedea_larsen.html",
        imageSource: "Image of 'Eyedea' Larsen via Heavy Blog is Heavy",
        additionalInfo: "Eyedea's music often delved into philosophy, psychology, and social issues, reflecting his thoughtful and introspective nature.",
        difficulty: 2
    },

    {
        id: "1012",
        lat: 44.1680805962643,
        lng: -94.00311590799822,
        name: "Hanging of the Dakota 38 (Dec 26, 1862)",
        title: "Hanging of the Dakota 38",
        image: "https://mnthen.com/markers/mankato/images/mankato_38.webp",
        creator: "Matt Reicher",
        city: "Mankato",
        audio: "/audio/mankato/man_dakota_38.mp3", 
        tours: "event",
        summary: "The 1862 Dakota War ended with the largest mass hanging in U.S. history—38 Dakota men—marking the fall of Native resistance in the region.",
        today: "Reconcilliation Park",
        link: "https://mnthen.com/blog/event/dakota_conflict.html",
        imageSource: "The Dakota 38 Memorial via Library of Congress",
        additionalInfo: "After the U.S.-Dakota War, 2,000 Dakota were captured; President Lincoln commuted the sentences of all but 39 of the 303 condemned to die.",
        difficulty: 1
    },

    {
        id: "1013",
        lat: 44.961337319371076,
        lng: -93.07148153924896,
        name: "Theodore Hamm Mansion (c. 1886 - 1954)",
        title: "Theodore Hamm Mansion",
        image: "https://mnthen.com/tour/hamm/gallery/mansion/hamm_mansion5.jpg",
        creator: "Matt Reicher",
        city: "St. Paul",
        audio: "/audio/exhibit/hamm_mansion.mp3", 
        tours: "history",
        summary: "The grand Theodore Hamm mansion in St. Paul, built in the late 1800s as a symbol of the family’s wealth, was destroyed by fire in 1954.",
        today: "Upper Swede Hollow Park",
        link: "https://mnthen.com/blog/place/stp_hamm_mansion.html",
        imageSource: "The Hamm Mansion via 1889 Victorian House Restoration",
        additionalInfo: "In 1976, the site of the Theodore Hamm Mansion became Upper Swede Hollow Park, honoring the family's contributions to St. Paul.",
        difficulty: 1
    },

    {
        id: "1014",
        lat: 44.98463074655949,
        lng: -93.26445659478223,
        name: "Father Louis Hennepin Suspension Bridge",
        title: "Father Louis Hennepin Suspension Bridge",
        image: "https://mnthen.com/locations/gallery/mpls/henn_bridge/henn_bridge_1.jpg",
        creator: "Matt Reicher",
        city: "Minneapolis",
        audio: "/audio/exhibit/hennepin.mp3", 
        tours: "place",
        summary: "Built in 1855, the Father Louis Hennepin Bridge was the first to span the Mississippi above St. Anthony Falls, fueling Minneapolis's growth.",
        today: "Downtown Minneapolis",
        link: "https://www.mnopedia.org/structure/father-louis-hennepin-suspension-bridge",
        imageSource: "First suspension bridge in Minneapolis, (c. 1858) via MNopedia",
        additionalInfo: "The original bridge was a suspension bridge, a relatively new and innovative design at the time.",
        difficulty: 1
    },

    {
        id: "1015",
        lat: 44.95463990008291,
        lng: -93.10223181529494,
        name: "Minnesota’s Third State Capitol",
        title: "Minnesota’s Third State Capitol",
        image: "https://mnthen.com/exhibit/images/capitol3.jpg",
        creator: "Brian C. Pease",
        city: "St. Paul",
        audio: "/audio/exhibit/capitol3.mp3",
        tours: "place",
        summary: "Minnesota’s third state capitol, built 1896–1905 by Cass Gilbert, blends artistry and innovation. Restorations preserved its historic beauty.",
        today: "St. Paul's North End",
        link: "https://www.mnopedia.org/structure/minnesota-s-third-state-capitol",
        imageSource: "Minnesota State Capitol Building (2022)",
        additionalInfo: "The Capitol’s dome is the second-largest self-supported marble dome in the world, after St. Peter's Basilica in Vatican City.",
        difficulty: 1
    },

    {
        id: "1016",
        lat: 44.893943004662326,
        lng: -93.18772007741772,
        name: "Whiskey the Horse (c. 1911 - 1943)",
        title: "Whiskey the Horse (c. 1911 - 1943)",
        image: "https://mnthen.com/images/whiskey.jpg",
        creator: "Matt Reicher",
        city: "St. Paul",
        audio: "/audio/exhibit/whiskey.mp3",
        tours: "person",
        summary: "Whiskey, a rebellious Army horse, became a famed jumper under Lt. Hazelrigg at Fort Snelling. They stayed bonded until Whiskey’s death in 1943.",
        today: "Near the Visitor Center",
        link: "https://mnthen.com/blog/people/whiskey.html",
        imageSource: "Whiskey with Captain W.R. Hazelrigg (1943)",
        additionalInfo: "Whiskey was buried with full military honors, marking the end of an era where horses played a significant role in the U.S. Army.",
        difficulty: 1
    },

    {
        id: "1017",
        lat: 44.96153652405189,
        lng: -93.07320192008716,
        name: "Swede Hollow (Pre-1839: Unknown - 1956)",
        title: "Swede Hollow",
        image: "https://mnthen.com/tour/hamm/gallery/hollow/hamm_hollow1.jpg",
        creator: "Matt Reicher",
        city: "St. Paul",
        audio: "/audio/exhibit/swede_hollow.mp3",
        tours: "place",
        summary: "From the 1850s to 1956, Swede Hollow was a St. Paul immigrant enclave. Lacking plumbing or power, it still fostered a close-knit community.",
        today: "Swede Hollow Park",
        link: "https://www.mnopedia.org/place/swede-hollow",
        imageSource: "Swede Hollow looking north, (c.1910). via MNopedia",
        additionalInfo: "In 1976, Swede Hollow was transformed into a nature sanctuary with trails and signs commemorating the communities that once lived there.",
        difficulty: 2
    },

    {
        id: "1018",
        lat: 44.956571587648774,
        lng: -93.10028134083977,
        name: "William R. Merriam Mansion (1882 - 1896)",
        title: "William R. Merriam Mansion",
        image: "https://mnthen.com/images/merriam_house.jpg",
        creator: "Matt Reicher",
        city: "St. Paul",
        audio: "/audio/exhibit/merriam_mansion.mp3",
        tours: "history",
        summary: "In 1880, William R. Merriam built a grand Queen Anne mansion in St. Paul. A social hub, it was tragically destroyed by fire in 1896.",
        today: "Cass Gilbert Park",
        link: "https://mnthen.com/blog/place/merriam_mansion.html",
        imageSource: "William R. Merriam residence, (c.1890). via St Paul Historical",
        additionalInfo: "After serving as Minnesota's governor, Merriam was appointed by President McKinley to direct the U.S. Census Bureau in 1899.",
        difficulty: 1
    },
    
    {
        "id": "1019",
        "lat": 45.08421675605315,
        "lng": -92.78683662323817,
        "name": "St. Croix Boom Site (1856 - 1914)",
        "title": "St. Croix Boom Site",
        "image": "https://mnthen.com/images/boom1.jpg",
        "creator": "Matt Reicher",
        "city": "Stillwater",
        "audio": "/audio/exhibit/boomsite.mp3",
        "tours": "place",
        "summary": "The St. Croix Boom Site marked Minnesota’s lumber peak, processing 15B feet of logs before closing in 1914 due to deforestation and change.",
        "today": "Three miles north of downtown Stillwater on 95.",
        "link": "https://mnthen.com/blog/place/boomsite.html",
        "imageSource": "Men working the boom via the Forest Lake Times",
        "additionalInfo": "Recent efforts to clean up and preserve the St. Croix Boom Site have helped highlight its natural beauty and historical significance.",
        difficulty: 1
    },

{
        id: "1020",
        lat: 44.92708547231108,
        lng: -93.11986294501678,
        name: "Morgan, Samuel Huntington (1911 - 2000)",
        title: "Morgan, Samuel Huntington",
        image: "https://mnthen.com/images/exhibit/morgan.jpg",
        creator: "Matt Reicher",
        city: "St. Paul",
        audio: "/audio/exhibit/morgan.mp3", 
        tours: "person",
        summary: "Samuel Huntington Morgan championed preservation, creating parks and trails like Fort Snelling and Gateway Trail, leaving a lasting legacy.",
        today: "Intersection of Shepard Rd. and Randolph",
        link: "https://www.mnopedia.org/person/morgan-samuel-huntington-1911-2000",
        imageSource: "Image of Samuel H. Morgan, ca 1990s. via MNOpedia",
        additionalInfo: "The Samuel H. Morgan Land Fund supports Minnesota land conservation by funding acquisitions to expand state parks, public trails, and green spaces.",
        difficulty: 1
},
/*
   {
        id: "1021",
        lat: 44.95552119293967,
        lng: -93.15009997756202,
        name: "Prom Ballroom (1941 - 1987)",
        title: "Prom Ballroom",
        image: "https://mnthen.com/images/prom1.webp",
        creator: "Matt Reicher",
        city: "St. Paul",
        audio: "/audio/exhibit/prom.mp3",
        tours: "place",
        summary: "The Prom Ballroom was a popular dance venue featuring famous musicians like Glenn Miller and Buddy Holly, before declining with suburban growth and eventually being demolished.",
        today: "1190 University Ave W in Saint Paul",
        link: "https://mnthen.com/blog/place/prom.html",
        imageSource: "Image of the Prom Ballroom via Discogs",
        additionalInfo: "The Beach Boys performed at the Prom Ballroom on August 2, 1963, during their first major nationwide tour."
    },
*/
    {
        id: "1022",
        lat: 44.7695002003817,
        lng: -92.90470981679262,
        name: "Nininger",
        title: "Nininger",
        image: "https://mnthen.com/images/exhibit/nininger.jpg",
        creator: "Matt Reicher",
        city: "Hastings",
        audio: "/audio/exhibit/nininger.mp3",
        tours: "place",
        summary: "Nininger, founded in 1856 by John Nininger and backed by Ignatius Donnelly, boomed briefly before the 1857 Panic and was abandoned by 1869.",
        today: "Nininger Town Hall, Hastings",
        link: "https://www3.mnhs.org/mnopedia/search/index/place/nininger",
        imageSource: "Cyanotype photograph of Nininger c.1890 via MNopedia",
        additionalInfo: "Ignatius Donnelly later became famous for his writings on Atlantis, theories about Shakespeare’s works, and his political career.",
        difficulty: 1
    },

    {
      "id": "1023",
      "lat": 44.97998830008001,
      "lng": -93.25704091894147,
      "name": "Washburn ‘A’ Mill Explosion (May 2, 1878)",
      "title": "Washburn ‘A’ Mill Explosion",
      "image": "https://mnthen.com/images/mill-explosion.webp",
      "creator": "Matt Reicher",
      "city": "Minneapolis",
      "audio": "/audio/exhibit/washburn.mp3",
      "tours": "event",
      "summary": "The 1878 explosion at Minneapolis’ Washburn ‘A’ Mill killed 18. The disaster shocked the city and led to new safety measures in industry.",
      "today": "Mill Ruins Park",
      "link": "https://mnthen.com/blog/event/washburn_mill.html",
      "imageSource": "Washburn Mill Explosion via General Mills",
      "additionalInfo": "In 1928, Washburn-Crosby Company merged with several other regional milling companies to form General Mills, which remains a major food corporation today.",
      difficulty: 1
    },
    {
  "id": "1024",
  "lat": 44.45572863141056,
  "lng": -93.16030365602623,
  "name": "Northfield Bank Raid (September 7, 1876)",
  "title": "Northfield Bank Raid",
  "image": "https://mnthen.com/images/northfield.jpg",
  "creator": "Matt Reicher",
  "city": "Northfield",
  "audio": "/audio/northfield.mp3",
  "tours": "event",
  "summary": "In 1876, Jesse James’ gang botched a Northfield bank robbery as armed townsfolk fought back. Two died, the Youngers were caught, Jesse escaped.",
  "today": "Northfield History Center",
  "link": "https://mnthen.com/blog/event/northfield.html",
  "imageSource": "Northfield Bank Raid 1876 via Northfield History Center",
  "additionalInfo": "Despite being shot 11 times during the raid and manhunt, Cole Younger survived—only to spend 25 years in prison before being pardoned."
},

{
  "id": "1025",
  "lat": 45.08605825417038,
  "lng": -92.99964796360983,
  "name": "Erd-Geist Gazebo",
  "title": "Erd-Geist Gazebo",
  "image": "https://mnthen.com/images/exhibit/gazebo.jpg",
  "creator": "Matt Reicher",
  "city": "White Bear Lake",
  "audio": "https://mnthen.com/audio/exhibit/geist.mp3",
  "tours": "place",
  "summary": "The Erd-Geist Gazebo, built in 1883 as a wedding gift, was originally on White Bear Lake’s south shore and now stands in Matoska Park.",
  "today": "Matoska Park alongside White Bear Lake",
  "link": "https://mnthen.com/blog/place/geist.html",
  "imageSource": "Geist Gazebo, White Bear Lake(1885) via MN Digital Library",
  "additionalInfo": "Local legend has it that the gazebo was moved across the frozen White Bear Lake in 1974. However, the ice was deemed too thin to safely support the structure and the plan was changed.",
    difficulty: 2
},

{
  "id": "1026",
  "lat": 44.94271592233145,
  "lng": -93.09783889422603,
  "name": "Nina Clifford (c. 1851 - 1929)",
  "title": "Nina Clifford",
  "image": "https://mnthen.com/images/gangster/clifford/clifford1.jpg",
  "creator": "Matt Reicher",
  "city": "St. Paul",
  "audio": "/audio/exhibit/clifford.mp3",
  "tours": "person",
  "summary": "In the 1890s, Nina Clifford ran St. Paul’s top brothel, becoming a wealthy businesswoman and philanthropist who defied Victorian norms.",
  "today": "Downtown St. Paul",
  "link": "https://mnthen.com/blog/people/clifford.html",
  "imageSource": "Image of Clifford’s brothel via MNopedia",
  "additionalInfo": "Legend claimed secret tunnels connected Clifford's brothel to the exclusive Minnesota Club, though this was later debunked.",
    difficulty: 1
},
{
  "id": "1027",
  "lat": 44.91348615039166,
  "lng": -93.13984099221071,
  "name": "Summit Brewing Company",
  "title": "Summit Brewing Company",
  "image": "https://mnthen.com/images/exhibit/today/summit_now.jpg",
  "creator": "Matt Reicher",
  "city": "St. Paul",
  "audio": "/audio/exhibit/summit.mp3",
  "tours": "place",
  "summary": "Summit Brewing began in 1986 when Mark Stutrud turned a former St. Paul auto parts store into a brewery focused on unique, underrepresented beers.",
  "today": "Crosby Business Center",
  "link": "https://mnthen.com/blog/place/summit.html",
  "imageSource": "Summit Brewing Co. via All About Beer",
  "additionalInfo": "Summit founder Mark Stutrud retired as CEO in 2023 after 37 years, succeeded by former Chief Strategy Officer Brandon Bland.",
    difficulty: 1
},

{
  "id": "1028",
  "lat": 44.95354376638059,
  "lng": -93.09708926359092,
  "name": "Downtown Ballpark (Pillbox) 1903 - 1909",
  "title": "Downtown Ballpark (Pillbox)",
  "image": "https://mnthen.com/images/exhibit/pillbox.jpg",
  "creator": "Matt Reicher",
  "city": "St. Paul",
  "audio": "/audio/exhibit/pillbox.mp3",
  "tours": "history",
  "summary": "\“The Pillbox,\” St. Paul’s Downtown Ballpark (1903–09), had tiny dimensions—just 210 feet to right field—before being abandoned and sold.",
  "today": "State Capitol Complex",
  "link": "https://mnthen.com/blog/place/pillbox.html",
  "imageSource": "Pillbox (1903) via MPR News",
  "additionalInfo": "Hall of Famer Andrew \"Rube\" Foster threw a no-hitter for the St. Paul Colored Gophers at the Pillbox in 1908.",
    difficulty: 1
},

{
  "id": "1029",
  "lat": 44.9621358458752,
  "lng": -93.07103242234,
  "name": "William Hamm Jr. Kidnapping (June 15-19, 1933)",
  "title": "William Hamm Jr. Kidnapping",
  "image": "https://mnthen.com/tour/hamm/gallery/kidnap/hamm_kidnap1.jpg",
  "creator": "Matt Reicher",
  "city": "St. Paul",
  "audio": "/audio/exhibit/hamm_kidnap.mp3",
  "tours": "event",
  "summary": "On June 15, 1933, the Barker-Karpis Gang kidnapped Hamm’s Brewing president William Hamm Jr. He was released unharmed after a $100,000 ransom.",
  "today": "Near St. Paul Brewing Co.",
  "link": "https://mnthen.com/blog/event/hamm_kidnap.html",
  "imageSource": "Investigators inspect the home of Theodore Hamm via 1889 Minnesota Good Age",
  "additionalInfo": "The Barker-Karpis gang brought in a strategist from Al Capone's Chicago syndicate to help plan Hamm Jr.'s kidnapping.",
    difficulty: 1
},

{
  "id": "1030",
  "lat": 44.987154491771946,
  "lng": -93.25850396437934,
  "name": "Nye's Polonaise Room (1950 - 2016)",
  "title": "Nye's Polonaise Room",
  "image": "https://mnthen.com/images/nyes.webp",
  "creator": "Matt Reicher",
  "city": "Minneapolis",
  "audio": "/audio/exhibit/nyes.mp3",
  "tours": "place",
  "summary": "Nye's Polonaise Room (1950–2016) was a beloved Minneapolis Polish bar with polka music, a piano lounge, legendary staff, and a welcoming vibe.",
  "today": "On East Hennepin Ave. in NE Minneapolis",
  "link": "https://mnthen.com/blog/place/nyes.html",
  "imageSource": "Nye's Polonaise Room, Minneapolis, March 27, 2009 via MPRNews",
  "additionalInfo": "Guy Fieri featured Nye's on Season 13 of Food Network’s \"Diners, Drive-Ins and Dives,\" praising their pierogi and prime rib sandwich.",
    difficulty: 1
},

{
  "id": "1031",
  "lat": 45.20298779768933,
  "lng": -96.01921054075744,
  "name": "Appleton, MN: A Living Memorial (1947 - Present)",
  "title": "Appleton, MN: A Living Memorial",
  "image": "https://mnthen.com/images/exhibit/apple1.jpg",
  "creator": "Matt Reicher",
  "city": "Appleton",
  "audio": "/audio/exhibit/appleton.mp3",
  "tours": "place",
  "summary": "Appleton transformed its street grid into a \“living memorial,\” naming streets after fallen soldiers to honor them in daily life.",
  "today": "Appleton Veterans Memorial",
  "link": "https://mnthen.com/blog/place/appleton.html",
  "imageSource": "Street signs denoting the names of fallen veterans via Appleton Website",
  "additionalInfo": "Some streets carry not just one name, but several from the same family—like Werring and Nelson Avenues—honoring brothers and cousins who died in war.",
    difficulty: 1
}


    // Add more locations here
];
